package com.gaecompat.tests.graphics;

import static org.junit.Assert.*;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;

import org.junit.Test;

import com.google.appengine.repackaged.com.google.common.io.Files;
import com.google.code.appengine.awt.Color;
import com.google.code.appengine.awt.Graphics2D;
import com.google.code.appengine.awt.image.BufferedImage;

public class DrawingTest {

	@Test
	public void testBasicDrawing() throws IOException {
		
		int iw = 400, ih = 400;
		int rw = 200, rh = 200;
		BufferedImage image = new BufferedImage(iw, ih, BufferedImage.TYPE_INT_RGB);
		Graphics2D g2d = image.createGraphics();
		
		g2d.setColor(Color.red);
		g2d.fillRect(0, 0, rw, rh);
		g2d.setColor(Color.green);
		g2d.fillRect(rw, 0, rw, rh);
		g2d.setColor(Color.blue);
		g2d.fillRect(0, rh, rw, rh);
		g2d.setColor(Color.black);
		g2d.fillRect(rw, rh, rw, rh);
		
		File outfile = File.createTempFile("graphicsimage", ".png");
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		try {
			com.google.code.appengine.imageio.ImageIO.write(image, "png", out);
			byte[] bytes = out.toByteArray();
			assertTrue(bytes.length > 0); // TODO check pixel by pixel that it equals image generated by TestData.generateImage 
			Files.write(bytes, outfile);
		} finally {
			outfile.delete();
		}
		
	}

	@Test
	public void testDrawString() throws IOException {
		BufferedImage image = new BufferedImage(400, 400, BufferedImage.TYPE_INT_RGB);
		
		Graphics2D g = image.createGraphics();
		
		g.drawString("hello, world", 100, 100);
	}
		
}
